#!/usr/bin/env bash
#display the requested info from /etc/passwd using while loop
while IFS=: read -r username _ userid _ homedir _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
    echo
done < /etc/passwd

