#!/usr/bin/env bash
#create /var/run/myscript.pid
#display To infinity and beyond
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo bash -c "echo $$ > /var/run/myscript.pid"

# Define trap handlers for signals
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; sudo rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'sudo rm -f /var/run/myscript.pid; exit' SIGQUIT

# Infinite loop
while :
do
    echo "To infinity and beyond"
    sleep 2
done
